#server:
#  port: 10088
#  servlet:
#    context-path: /chk-auth
#spring:
#  cloud:
#    #配置nacos注册中心
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: chk-auth
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    password: 802386
